[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs_20"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist",
    "npm ci --omit=dev"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "sh start.sh"
