# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d24b5843b7042c620107939e3dee6b12"
name = "Webhook Monitor"
handle = "swishtag-webhook-monitor"

application_url = "https://shopify-webhook-monitoring-production.up.railway.app"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_fulfillments,write_fulfillments,read_inventory,read_metaobject_definitions,read_metaobjects,read_online_store_pages,write_online_store_pages,read_orders,write_orders,read_products,write_products,read_script_tags,write_script_tags,read_content,write_content,read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://shopify-webhook-monitoring-production.up.railway.app/authenticate" ]
